# H2 database config
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
# Enable/disable SQL commands during dev in agroal database connection pool
#%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT
quarkus.http.cors.headers=content-type
quarkus.http.cors.access-control-allow-credentials=true

# Desperate debugging...
#quarkus.log.level=DEBUG
#quarkus.arc.log=DEBUG
#quarkus.log.category."io.quarkus.arc.impl".level=DEBUG
#quarkus.log.category."org.acme".level=DEBUG
#quarkus.log.level=DEBUG

# Quarkus Mailer config
quarkus.mailer.from=noreply@yourdomain.com
quarkus.mailer.host=smtp.mailtrap.io
quarkus.mailer.port=587
quarkus.mailer.username=your_mailtrap_inbox_username
quarkus.mailer.password=your_mailtrap_inbox_password
quarkus.mailer.ssl=false
quarkus.mailer.start-tls=required
quarkus.mailer.mock=true

# Notification client base URL
quarkus.rest-client.notification-client.url=http://127.0.0.1:3010

